// utils/foodItems.js
// Auto-generated from FOOD_data_for_bills.xlsx
// price is intentionally left out - staff enters it manually while billing

export const foodItems = [
    { id: 1, name: "MANCHOW SOUP" },
    { id: 2, name: "HOT & SOUR SOUP" },
    { id: 3, name: "SWEET CORN SOUP" },
    { id: 4, name: "CORIANDER SOUP" },
    { id: 5, name: "CLEAR SOUP" },
    { id: 6, name: "CHICKEN SAATE" },
    { id: 7, name: "CHICKEN 65" },
    { id: 8, name: "CHICKEN RED PEPPER" },
    { id: 9, name: "BAR BQ CHICKEN" },
    { id: 10, name: "OYSTER CHICKEN CHILLY" },
    { id: 11, name: "APPLE CHICKEN" },
    { id: 12, name: "CHICKEN CRUNCHY" },
    { id: 13, name: "CHICKEN CHRISPY" },
    { id: 14, name: "CHICKEN LOLLIPOP" },
    { id: 15, name: "FISH FINGER (BASA)" },
    { id: 16, name: "VEG HOT GARLIC" },
    { id: 17, name: "VEG GOLD COIN" },
    { id: 18, name: "VEG CRUNCHY" },
    { id: 19, name: "PANEER SAATE" },
    { id: 20, name: "DRAGON ROLL" },
    { id: 21, name: "KUM FO PNR" },
    { id: 22, name: "MUSH CHILLY" },
    { id: 23, name: "BABYCORN MUSH CHILLY" },
    { id: 24, name: "SANGHAI POTATO" },
    { id: 25, name: "VEG CHEESE BALL" },
    { id: 26, name: "GOBI MANCHURIAN" },
    { id: 27, name: "CHICKEN MANCHURIAN" },
    { id: 28, name: "CHICKEN CHILLY" },
    { id: 29, name: "CHICKEN SCHEZWAN" },
    { id: 30, name: "CHICKEN SPRING ROLL" },
    { id: 31, name: "VEG MANCHURIAN" },
    { id: 32, name: "VEG CHILLY" },
    { id: 33, name: "VEG SCHEZWAN" },
    { id: 34, name: "VEG SPRING ROLL" },
    { id: 35, name: "VEG LOLLIPOP" },
    { id: 36, name: "PANEER MANCHURIAN" },
    { id: 37, name: "PANEER CHILLY" },
    { id: 38, name: "PANEER SCHEZWAN" },
    { id: 39, name: "PANEER SPRING ROLL" },
    { id: 40, name: "PANEER LOLLIPOP" },
    { id: 41, name: "CHICKEN FRIED RICE" },
    { id: 42, name: "CHICKEN SZW FRIED RICE" },
    { id: 43, name: "CHICKEN HAKKA NOOD" },
    { id: 44, name: "CHICKEN SZW HAKKA NOOD" },
    { id: 45, name: "CHICKEN TRIPPLE FRIED RICE" },
    { id: 46, name: "CHICKEN BURNT GARLIC RICE" },
    { id: 47, name: "CHICKEN BURNT GARLIC NOOD" },
    { id: 48, name: "CHICKEN MIX FRIED RICE" },
    { id: 49, name: "VEG FRIED RICE" },
    { id: 50, name: "VEG SZW FRIED RICE" },
    { id: 51, name: "VEG HAKKA NOOD" },
    { id: 52, name: "VEG SZW HAKKA NOOD" },
    { id: 53, name: "VEG TRIPPLE FRIED RICE" },
    { id: 54, name: "VEG BURNT GARLIC RICE" },
    { id: 55, name: "VEG BURNT GARLIC NOOD" },
    { id: 56, name: "VEG MIX FRIED RICE" },
    { id: 57, name: "EGG FRIED RICE" },
    { id: 58, name: "EGG SZW FRIED RICE" },
    { id: 59, name: "EGG HAKKA NOOD" },
    { id: 60, name: "EGG SZW HAKKA NOOD" },
    { id: 61, name: "EGG TRIPPLE FRIED RICE" },
    { id: 62, name: "EGG BURNT GARLIC RICE" },
    { id: 63, name: "EGG BURNT GARLIC NOOD" },
    { id: 64, name: "EGG MIX FRIED RICE" },
    { id: 65, name: "PWN FRIED RICE" },
    { id: 66, name: "PWN SZW FRIED RICE" },
    { id: 67, name: "PWN HAKKA NOOD" },
    { id: 68, name: "PWN SZW HAKKA NOOD" },
    { id: 69, name: "PWN TRIPPLE FRIED RICE" },
    { id: 70, name: "PWN BURNT GARLIC RICE" },
    { id: 71, name: "PWN BURNT GARLIC NOOD" },
    { id: 72, name: "PWN MIX FRIED RICE" },
    { id: 73, name: "PANNER FRIED RICE" },
    { id: 74, name: "POMFRET TANDOORI" },
    { id: 75, name: "PRAWANS TIKKA" },
    { id: 76, name: "BANGDA TANDOORI" },
    { id: 77, name: "FISH TIKKA (BASA)" },
    { id: 78, name: "POMFRET GREEN TNDR" },
    { id: 79, name: "CHI TANDOORI HALF" },
    { id: 80, name: "CHI TANDOORI FULL" },
    { id: 81, name: "CHI KALIMIRI TNDR HALF" },
    { id: 82, name: "CHI KALIMIRI TNDR FULL" },
    { id: 83, name: "ANGARA TIKKA" },
    { id: 84, name: "CHI SEEKH KABAB" },
    { id: 85, name: "CHI TANGADI KABAB (2PCS)" },
    { id: 86, name: "CHI PAHADI KABAB" },
    { id: 87, name: "CHI MALAI KABAB" },
    { id: 88, name: "CHI RESHMI KABAB" },
    { id: 89, name: "CHI KALIMIRI KABAB" },
    { id: 90, name: "CHI LASUNI TIKKA" },
    { id: 91, name: "BHARA HUA TIKKA" },
    { id: 92, name: "CHI JEERA KABAB" },
    { id: 93, name: "CHI NOORANI KABAB" },
    { id: 94, name: "CHI BANJARA KABAB" },
    { id: 95, name: "CHI KASTURI KABAB" },
    { id: 96, name: "CHI PUDINA KABAB" },
    { id: 97, name: "SOLAY KABAB" },
    { id: 98, name: "HASEENA KABAB" },
    { id: 99, name: "VEG HARA BHARA KABAB" },
    { id: 100, name: "MUSH/BABYCORN TNDR" },
    { id: 101, name: "VEG SEEKH KABAB" },
    { id: 102, name: "ALOO METHI TIKKI" },
    { id: 103, name: "PANEER TIKKA" },
    { id: 104, name: "PALAK CORN TIKKI" },
    { id: 105, name: "PANEER PAHADI TIKKA" },
    { id: 106, name: "TANDOORI ALOO/GOBI" },
    { id: 107, name: "PANEER MALAI TIKKA" },
    { id: 108, name: "CHEESE PAKODA" },
    { id: 109, name: "BHARA HUA PANEER" },
    { id: 110, name: "PANEER PASANDA KABAB" },
    { id: 111, name: "BHARA HUA ALOO" },
    { id: 112, name: "VEG PLATTER" },
    { id: 113, name: "SHAHI PANEER" },
    { id: 114, name: "PNR BUTTER MASALA" },
    { id: 115, name: "PANEER MUTTER" },
    { id: 116, name: "DUM ALU GOBI" },
    { id: 117, name: "MAKAI PALAK" },
    { id: 118, name: "PANEER MUSSALLAM" },
    { id: 119, name: "TAWE WALI SABJI" },
    { id: 120, name: "DAHI PAKODA KADHI" },
    { id: 121, name: "TAWA MUSHROOM" },
    { id: 122, name: "VEG HANDI" },
    { id: 123, name: "VEG KOLHAPURI" },
    { id: 124, name: "VEG CHILLI MILI" },
    { id: 125, name: "VEG TRINGA" },
    { id: 126, name: "PNR TIKKA MASALA" },
    { id: 127, name: "VEG LAHORI" },
    { id: 128, name: "PNR KADAI" },
    { id: 129, name: "VEG KADAI" },
    { id: 130, name: "VEG SABNAM" },
    { id: 131, name: "PANEER PASANDA" },
    { id: 132, name: "PNR KOLHAPURI" },
    { id: 133, name: "PNR BHURJI" },
    { id: 134, name: "MALAI KOFTA" },
    { id: 135, name: "VEG KOFTA" },
    { id: 136, name: "BAINGAN BHARTA" },
    { id: 137, name: "MUTTON PESAWARI" },
    { id: 138, name: "MUTTON RARA" },
    { id: 139, name: "MUTTON BHUNA" },
    { id: 140, name: "MUTTON ROGAN JOSH" },
    { id: 141, name: "MUTTON MASALA" },
    { id: 142, name: "MUTTON HANDI HALF" },
    { id: 143, name: "MUTTON HANDI FULL" },
    { id: 144, name: "MUTTON KEEMA" },
    { id: 145, name: "MUTTON TAWA MSL" },
    { id: 146, name: "MAKHANWALA MURG" },
    { id: 147, name: "AMBARSARIYA MURG" },
    { id: 148, name: "MURG LAHORI" },
    { id: 149, name: "KADAI MURG" },
    { id: 150, name: "RARA MURG" },
    { id: 151, name: "BHUNA MURG" },
    { id: 152, name: "MURG KALIMIRCH" },
    { id: 153, name: "CHICKEN TIKKA MSL" },
    { id: 154, name: "CHI KOLHAPURI" },
    { id: 155, name: "TAWA CHICKEN" },
    { id: 156, name: "CHI MASALA/DRY" },
    { id: 157, name: "MURG METHI MASALA" },
    { id: 158, name: "CHI SUKKA" },
    { id: 159, name: "CHI PATIYALA" },
    { id: 160, name: "CHI ANGARA" },
    { id: 161, name: "CHI HYDRABDI" },
    { id: 162, name: "CHI KEEMA" },
    { id: 163, name: "MURG SAAGWALA" },
    { id: 164, name: "TARIWALA MURG" },
    { id: 165, name: "BARSATI MURG HALF" },
    { id: 166, name: "BARSATI MURG FULL" },
    { id: 167, name: "CHI HANDI HALF" },
    { id: 168, name: "CHI HANDI FULL" },
    { id: 169, name: "MURG MUSALLAM HALF" },
    { id: 170, name: "MURG MUSALLAM FULL" },
    { id: 171, name: "SPL. PRAWNS SUKKA" },
    { id: 172, name: "PRAWNS MASALA" },
    { id: 173, name: "PRAWNS GOAN CURRY" },
    { id: 174, name: "PRAWNS DRY" },
    { id: 175, name: "POMFRET MASALA" },
    { id: 176, name: "POMFRET GOAN CURRY" },
    { id: 177, name: "POMFRET GREEN MASALA" },
    { id: 178, name: "SURMAI MASALA" },
    { id: 179, name: "SURMAI GOAN CURRY" },
    { id: 180, name: "BANGDA MASALA" },
    { id: 181, name: "TISRYA MASALA" },
    { id: 182, name: "TISRYA DRY" },
    { id: 183, name: "POMFRET/SURMAI MASALA" },
    { id: 184, name: "BOMBIL MASALA" },
    { id: 185, name: "MANDELI/JAULA MASALA" },
    { id: 186, name: "PRAWNS KOLIWADA" },
    { id: 187, name: "PRAWNS RAWA FRY" },
    { id: 188, name: "PRAWNS TAWA FRY" },
    { id: 189, name: "CHICKEN MSL" },
    { id: 190, name: "CHICKEN SAGUTI" },
    { id: 191, name: "SPECIAL CHICKEN" },
    { id: 192, name: "CHICKEN KOLHAPURI" },
    { id: 193, name: "CHICKEN HANDI HALF" },
    { id: 194, name: "CHICKEN HANDI FULL" },
    { id: 195, name: "CHICKEN LEG DRY" },
    { id: 196, name: "CHICKEN TAWA" },
    { id: 197, name: "MUTTON KEEMA DRY" },
    { id: 198, name: "MUTTON MSL DRY" },
    { id: 199, name: "DRY MUTTON" },
    { id: 200, name: "CHICKEN BIRYANI" },
    { id: 201, name: "EGG BIRYANI" },
    { id: 202, name: "MUTTON BIRYANI" },
    { id: 203, name: "PRAWNS BIRYANI" },
    { id: 204, name: "VEG BIRYANI" },
    { id: 205, name: "VEG PULAV" },
    { id: 206, name: "PANEER BIRYANI" },
    { id: 207, name: "SEAFOOD BIRYANI" },
    { id: 208, name: "CHI BIRYANI B/L" },
    { id: 209, name: "VEG CHILLY GARLIC RICE" },
    { id: 210, name: "VEG CHILLY GARLIC NOODLE" },
    { id: 211, name: "VEG HONGKON FRIED RICE" },
    { id: 212, name: "VEG HONGKON FRIED NOODLE" },
    { id: 213, name: "VEG SINGAPORE NOODLE" },
    { id: 214, name: "VEG SINGAPORE RICE" },
    { id: 215, name: "VEG CHOPPER RICE" },
    { id: 216, name: "CHI CHILLY GARLIC RICE" },
    { id: 217, name: "CHI CHILLY GARLIC NOODLE" },
    { id: 218, name: "CHI HONGKON FRIED RICE" },
    { id: 219, name: "CHI HONGKON FRIED NOODLE" },
    { id: 220, name: "CHI SINGAPORE NOODLE" },
    { id: 221, name: "CHI SINGAPORE RICE" },
    { id: 222, name: "CHI CHOPPER RICE" },
    { id: 223, name: "POMFRET THALI" },
    { id: 224, name: "SURMAI THALI" },
    { id: 225, name: "PRAWNS THALI" },
    { id: 226, name: "BANGDA THALI" },
    { id: 227, name: "BOMBIL THALI" },
    { id: 228, name: "SEAFOOD THALI" },
    { id: 229, name: "CHICKEN THALI" },
    { id: 230, name: "CHICKEN THALI MAL." },
    { id: 231, name: "CHICKEN SPL THALI" },
    { id: 232, name: "MUTTON THALI" },
    { id: 233, name: "VEG THALI" },
    { id: 234, name: "VEG SPL THALI" },
    { id: 235, name: "GHEE RICE" },
    { id: 236, name: "JEERA RICE" },
    { id: 237, name: "STEAM RICE" },
    { id: 238, name: "CURD RICE" },
    { id: 239, name: "DAL KHICDI" },
    { id: 240, name: "DAL KHICHDI TADKA" },
    { id: 241, name: "ROTI" },
    { id: 242, name: "BUTTER ROTI" },
    { id: 243, name: "PARATHA" },
    { id: 244, name: "BTR PARATHA" },
    { id: 245, name: "NAAN" },
    { id: 246, name: "BUTTER NAAN" },
    { id: 247, name: "GARLIC NAAN" },
    { id: 248, name: "BUTTER GARLIC NAAN" },
    { id: 249, name: "CHEESE NAAN" },
    { id: 250, name: "CHEESE GARLIC NAAN" },
    { id: 251, name: "ROOMALI" },
    { id: 252, name: "BUTTER ROOMALI" },
    { id: 253, name: "EXTRA BUTTER" },
    { id: 254, name: "EXTRA CHEESE" },
    { id: 255, name: "DAL FRY" },
    { id: 256, name: "DAL TADKA" },
    { id: 257, name: "DAL MAKHANI" },
    { id: 258, name: "RAJMA" },
    { id: 259, name: "DAL PALAK" },
    { id: 260, name: "TAMATAR SHORBA" },
    { id: 261, name: "PALAK DA SHORBA" },
    { id: 262, name: "SABZI DA SHORBA" },
    { id: 263, name: "MURG DA SHORBA" },
    { id: 264, name: "BOONDI RAITA" },
    { id: 265, name: "PINEAPPLE RAITA" },
    { id: 266, name: "CUCUMBER RAITA" },
    { id: 267, name: "MIX RAITA" },
    { id: 268, name: "GULAB JAMUN" },
    { id: 269, name: "CARAMEL CUSTARD" },
    { id: 270, name: "VANILLA ICE CREAM" },
    { id: 271, name: "STRAWBERRY ICE CREAM" },
    { id: 272, name: "BUTTERSCOTCH ICE CREAM" },
    { id: 273, name: "CHOCOLATE ICE CREAM" },
    { id: 274, name: "BROWNIE" },
    { id: 275, name: "SPRITE 300ML" },
    { id: 276, name: "SPRITE 600ML" },
    { id: 277, name: "THUMBS UP 300ML" },
    { id: 278, name: "THUMBS UP 600ML" },
    { id: 279, name: "LIMCA 600ML" },
    { id: 280, name: "CAMPA 200ML" },
    { id: 281, name: "CAMPA 500ML" },
    { id: 282, name: "FRESH LIME SODA" },
    { id: 283, name: "FRESH LIME WATER" },
    { id: 284, name: "PKG DRINKING WATER 500ML" },
    { id: 285, name: "PKG DRINKING WATER 1L" },
];

export default foodItems;