// utils/liquorItems.js
// Auto-generated from liquor_data_for_bills.xlsx
// price is intentionally left out - staff enters it manually while billing

export const liquorItems = [
    { id: 1, name: "BLACK DOG GOLD 180ML", brand: "BLACK DOG GOLD", size: "180ml" },
    { id: 2, name: "BLACK DOG GOLD 90ML", brand: "BLACK DOG GOLD", size: "90ml" },
    { id: 3, name: "BLACK DOG GOLD 60ML", brand: "BLACK DOG GOLD", size: "60ml" },
    { id: 4, name: "BLACK DOG GOLD 30ML", brand: "BLACK DOG GOLD", size: "30ml" },
    { id: 5, name: "BLACK DOG CENTENARY 180ML", brand: "BLACK DOG CENTENARY", size: "180ml" },
    { id: 6, name: "BLACK DOG CENTENARY 90ML", brand: "BLACK DOG CENTENARY", size: "90ml" },
    { id: 7, name: "BLACK DOG CENTENARY 60ML", brand: "BLACK DOG CENTENARY", size: "60ml" },
    { id: 8, name: "BLACK DOG CENTENARY 30ML", brand: "BLACK DOG CENTENARY", size: "30ml" },
    { id: 9, name: "BLACK & WHITE 180ML", brand: "BLACK & WHITE", size: "180ml" },
    { id: 10, name: "BLACK & WHITE 90ML", brand: "BLACK & WHITE", size: "90ml" },
    { id: 11, name: "BLACK & WHITE 60ML", brand: "BLACK & WHITE", size: "60ml" },
    { id: 12, name: "BLACK & WHITE 30ML", brand: "BLACK & WHITE", size: "30ml" },
    { id: 13, name: "VAT 69 180ML", brand: "VAT 69", size: "180ml" },
    { id: 14, name: "VAT 69 90ML", brand: "VAT 69", size: "90ml" },
    { id: 15, name: "VAT 69 60ML", brand: "VAT 69", size: "60ml" },
    { id: 16, name: "VAT 69 30ML", brand: "VAT 69", size: "30ml" },
    { id: 17, name: "100 PIPERS 180ML", brand: "100 PIPERS", size: "180ml" },
    { id: 18, name: "100 PIPERS 90ML", brand: "100 PIPERS", size: "90ml" },
    { id: 19, name: "100 PIPERS 60ML", brand: "100 PIPERS", size: "60ml" },
    { id: 20, name: "100 PIPERS 30ML", brand: "100 PIPERS", size: "30ml" },
    { id: 21, name: "RED LABLE 180ML", brand: "RED LABLE", size: "180ml" },
    { id: 22, name: "RED LABLE 90ML", brand: "RED LABLE", size: "90ml" },
    { id: 23, name: "RED LABLE 60ML", brand: "RED LABLE", size: "60ml" },
    { id: 24, name: "RED LABLE 30ML", brand: "RED LABLE", size: "30ml" },
    { id: 25, name: "TEACHERS HIGHLAND 180ML", brand: "TEACHERS HIGHLAND", size: "180ml" },
    { id: 26, name: "TEACHERS HIGHLAND 90ML", brand: "TEACHERS HIGHLAND", size: "90ml" },
    { id: 27, name: "TEACHERS HIGHLAND 60ML", brand: "TEACHERS HIGHLAND", size: "60ml" },
    { id: 28, name: "TEACHERS HIGHLAND 30ML", brand: "TEACHERS HIGHLAND", size: "30ml" },
    { id: 29, name: "TEACHERS 50 180ML", brand: "TEACHERS 50", size: "180ml" },
    { id: 30, name: "TEACHERS 51 90ML", brand: "TEACHERS 51", size: "90ml" },
    { id: 31, name: "TEACHERS 52 60ML", brand: "TEACHERS 52", size: "60ml" },
    { id: 32, name: "TEACHERS 53 30ML", brand: "TEACHERS 53", size: "30ml" },
    { id: 33, name: "JAMESON 180ML", brand: "JAMESON", size: "180ml" },
    { id: 34, name: "JAMESON 90ML", brand: "JAMESON", size: "90ml" },
    { id: 35, name: "JAMESON 60ML", brand: "JAMESON", size: "60ml" },
    { id: 36, name: "JAMESON 30ML", brand: "JAMESON", size: "30ml" },
    { id: 37, name: "CHIVAS REGAL 180ML", brand: "CHIVAS REGAL", size: "180ml" },
    { id: 38, name: "CHIVAS REGAL 90ML", brand: "CHIVAS REGAL", size: "90ml" },
    { id: 39, name: "CHIVAS REGAL 60ML", brand: "CHIVAS REGAL", size: "60ml" },
    { id: 40, name: "CHIVAS REGAL 30ML", brand: "CHIVAS REGAL", size: "30ml" },
    { id: 41, name: "BALLANTINE 180ML", brand: "BALLANTINE", size: "180ml" },
    { id: 42, name: "BALLANTINE 90ML", brand: "BALLANTINE", size: "90ml" },
    { id: 43, name: "BALLANTINE 60ML", brand: "BALLANTINE", size: "60ml" },
    { id: 44, name: "BALLANTINE 30ML", brand: "BALLANTINE", size: "30ml" },
    { id: 45, name: "GLENWALK 180ML", brand: "GLENWALK", size: "180ml" },
    { id: 46, name: "GLENWALK 90ML", brand: "GLENWALK", size: "90ml" },
    { id: 47, name: "GLENWALK 60ML", brand: "GLENWALK", size: "60ml" },
    { id: 48, name: "GLENWALK 30ML", brand: "GLENWALK", size: "30ml" },
    { id: 49, name: "ANTIQUITY BLUE 180ML", brand: "ANTIQUITY BLUE", size: "180ml" },
    { id: 50, name: "ANTIQUITY BLUE 90ML", brand: "ANTIQUITY BLUE", size: "90ml" },
    { id: 51, name: "ANTIQUITY BLUE 60ML", brand: "ANTIQUITY BLUE", size: "60ml" },
    { id: 52, name: "ANTIQUITY BLUE 30ML", brand: "ANTIQUITY BLUE", size: "30ml" },
    { id: 53, name: "SIGNATURE 180ML", brand: "SIGNATURE", size: "180ml" },
    { id: 54, name: "SIGNATURE 90ML", brand: "SIGNATURE", size: "90ml" },
    { id: 55, name: "SIGNATURE 60ML", brand: "SIGNATURE", size: "60ml" },
    { id: 56, name: "SIGNATURE 30ML", brand: "SIGNATURE", size: "30ml" },
    { id: 57, name: "BLENDERS PRIDE 180ML", brand: "BLENDERS PRIDE", size: "180ml" },
    { id: 58, name: "BLENDERS PRIDE 90ML", brand: "BLENDERS PRIDE", size: "90ml" },
    { id: 59, name: "BLENDERS PRIDE 60ML", brand: "BLENDERS PRIDE", size: "60ml" },
    { id: 60, name: "BLENDERS PRIDE 30ML", brand: "BLENDERS PRIDE", size: "30ml" },
    { id: 61, name: "BLENDER PRIDE RESERVE 180ML", brand: "BLENDER PRIDE RESERVE", size: "180ml" },
    { id: 62, name: "BLENDER PRIDE RESERVE 90ML", brand: "BLENDER PRIDE RESERVE", size: "90ml" },
    { id: 63, name: "BLENDER PRIDE RESERVE 60ML", brand: "BLENDER PRIDE RESERVE", size: "60ml" },
    { id: 64, name: "BLENDER PRIDE RESERVE 30ML", brand: "BLENDER PRIDE RESERVE", size: "30ml" },
    { id: 65, name: "OAKSMIT GOLD 180ML", brand: "OAKSMIT GOLD", size: "180ml" },
    { id: 66, name: "OAKSMIT GOLD 90ML", brand: "OAKSMIT GOLD", size: "90ml" },
    { id: 67, name: "OAKSMIT GOLD 60ML", brand: "OAKSMIT GOLD", size: "60ml" },
    { id: 68, name: "OAKSMIT GOLD 30ML", brand: "OAKSMIT GOLD", size: "30ml" },
    { id: 69, name: "ROYAL CHALANGE 180ML", brand: "ROYAL CHALANGE", size: "180ml" },
    { id: 70, name: "ROYAL CHALANGE 90ML", brand: "ROYAL CHALANGE", size: "90ml" },
    { id: 71, name: "ROYAL CHALANGE 60ML", brand: "ROYAL CHALANGE", size: "60ml" },
    { id: 72, name: "ROYAL CHALANGE 30ML", brand: "ROYAL CHALANGE", size: "30ml" },
    { id: 73, name: "ROYAL STAG 180ML", brand: "ROYAL STAG", size: "180ml" },
    { id: 74, name: "ROYAL STAG 90ML", brand: "ROYAL STAG", size: "90ml" },
    { id: 75, name: "ROYAL STAG 60ML", brand: "ROYAL STAG", size: "60ml" },
    { id: 76, name: "ROYAL STAG 30ML", brand: "ROYAL STAG", size: "30ml" },
    { id: 77, name: "ROYAL STAG BARREL 180ML", brand: "ROYAL STAG BARREL", size: "180ml" },
    { id: 78, name: "ROYAL STAG BARREL 90ML", brand: "ROYAL STAG BARREL", size: "90ml" },
    { id: 79, name: "ROYAL STAG BARREL 60ML", brand: "ROYAL STAG BARREL", size: "60ml" },
    { id: 80, name: "ROYAL STAG BARREL 30ML", brand: "ROYAL STAG BARREL", size: "30ml" },
    { id: 81, name: "MCD NO1 180ML", brand: "MCD NO1", size: "180ml" },
    { id: 82, name: "MCD NO1 90ML", brand: "MCD NO1", size: "90ml" },
    { id: 83, name: "MCD NO1 60ML", brand: "MCD NO1", size: "60ml" },
    { id: 84, name: "MCD NO1 30ML", brand: "MCD NO1", size: "30ml" },
    { id: 85, name: "MCD LUX 180ML", brand: "MCD LUX", size: "180ml" },
    { id: 86, name: "MCD LUX 90ML", brand: "MCD LUX", size: "90ml" },
    { id: 87, name: "MCD LUX 60ML", brand: "MCD LUX", size: "60ml" },
    { id: 88, name: "MCD LUX 30ML", brand: "MCD LUX", size: "30ml" },
    { id: 89, name: "DSP BLACK 180ML", brand: "DSP BLACK", size: "180ml" },
    { id: 90, name: "DSP BLACK 90ML", brand: "DSP BLACK", size: "90ml" },
    { id: 91, name: "DSP BLACK 60ML", brand: "DSP BLACK", size: "60ml" },
    { id: 92, name: "DSP BLACK 30ML", brand: "DSP BLACK", size: "30ml" },
    { id: 93, name: "IMPERIAL BLUE 180ML", brand: "IMPERIAL BLUE", size: "180ml" },
    { id: 94, name: "IMPERIAL BLUE 90ML", brand: "IMPERIAL BLUE", size: "90ml" },
    { id: 95, name: "IMPERIAL BLUE 60ML", brand: "IMPERIAL BLUE", size: "60ml" },
    { id: 96, name: "IMPERIAL BLUE 30ML", brand: "IMPERIAL BLUE", size: "30ml" },
    { id: 97, name: "OAKSMITH SILVER 180ML", brand: "OAKSMITH SILVER", size: "180ml" },
    { id: 98, name: "OAKSMITH SILVER 90ML", brand: "OAKSMITH SILVER", size: "90ml" },
    { id: 99, name: "OAKSMITH SILVER 60ML", brand: "OAKSMITH SILVER", size: "60ml" },
    { id: 100, name: "OAKSMITH SILVER 30ML", brand: "OAKSMITH SILVER", size: "30ml" },
    { id: 101, name: "MASTER DELIGHT 180ML", brand: "MASTER DELIGHT", size: "180ml" },
    { id: 102, name: "MASTER DELIGHT 90ML", brand: "MASTER DELIGHT", size: "90ml" },
    { id: 103, name: "MASTER DELIGHT 60ML", brand: "MASTER DELIGHT", size: "60ml" },
    { id: 104, name: "MASTER DELIGHT 30ML", brand: "MASTER DELIGHT", size: "30ml" },
    { id: 105, name: "ABSOLUTE VODKA 180ML", brand: "ABSOLUTE VODKA", size: "180ml" },
    { id: 106, name: "ABSOLUTE VODKA 90ML", brand: "ABSOLUTE VODKA", size: "90ml" },
    { id: 107, name: "ABSOLUTE VODKA 60ML", brand: "ABSOLUTE VODKA", size: "60ml" },
    { id: 108, name: "ABSOLUTE VODKA 30ML", brand: "ABSOLUTE VODKA", size: "30ml" },
    { id: 109, name: "SMRINOFF 180ML", brand: "SMRINOFF", size: "180ml" },
    { id: 110, name: "SMRINOFF 90ML", brand: "SMRINOFF", size: "90ml" },
    { id: 111, name: "SMRINOFF 60ML", brand: "SMRINOFF", size: "60ml" },
    { id: 112, name: "SMRINOFF 30ML", brand: "SMRINOFF", size: "30ml" },
    { id: 113, name: "SMRINOFF APPLE 180ML", brand: "SMRINOFF APPLE", size: "180ml" },
    { id: 114, name: "SMRINOFF APPLE 90ML", brand: "SMRINOFF APPLE", size: "90ml" },
    { id: 115, name: "SMRINOFF APPLE 60ML", brand: "SMRINOFF APPLE", size: "60ml" },
    { id: 116, name: "SMRINOFF APPLE 30ML", brand: "SMRINOFF APPLE", size: "30ml" },
    { id: 117, name: "SMRINOFF JAMUN 180ML", brand: "SMRINOFF JAMUN", size: "180ml" },
    { id: 118, name: "SMRINOFF JAMUN 90ML", brand: "SMRINOFF JAMUN", size: "90ml" },
    { id: 119, name: "SMRINOFF JAMUN 60ML", brand: "SMRINOFF JAMUN", size: "60ml" },
    { id: 120, name: "SMRINOFF JAMUN 30ML", brand: "SMRINOFF JAMUN", size: "30ml" },
    { id: 121, name: "SMRINOFF MANGO MIRCHI 180ML", brand: "SMRINOFF MANGO MIRCHI", size: "180ml" },
    { id: 122, name: "SMRINOFF MANGO MIRCHI 90ML", brand: "SMRINOFF MANGO MIRCHI", size: "90ml" },
    { id: 123, name: "SMRINOFF MANGO MIRCHI 60ML", brand: "SMRINOFF MANGO MIRCHI", size: "60ml" },
    { id: 124, name: "SMRINOFF MANGO MIRCHI 30ML", brand: "SMRINOFF MANGO MIRCHI", size: "30ml" },
    { id: 125, name: "ROMANOV 180ML", brand: "ROMANOV", size: "180ml" },
    { id: 126, name: "ROMANOV 90ML", brand: "ROMANOV", size: "90ml" },
    { id: 127, name: "ROMANOV 60ML", brand: "ROMANOV", size: "60ml" },
    { id: 128, name: "ROMANOV 30ML", brand: "ROMANOV", size: "30ml" },
    { id: 129, name: "ROMANOV APPLE 180ML", brand: "ROMANOV APPLE", size: "180ml" },
    { id: 130, name: "ROMANOV APPLE 90ML", brand: "ROMANOV APPLE", size: "90ml" },
    { id: 131, name: "ROMANOV APPLE 60ML", brand: "ROMANOV APPLE", size: "60ml" },
    { id: 132, name: "ROMANOV APPLE 30ML", brand: "ROMANOV APPLE", size: "30ml" },
    { id: 133, name: "MAGIC MOVEMENT 180ML", brand: "MAGIC MOVEMENT", size: "180ml" },
    { id: 134, name: "MAGIC MOVEMENT 90ML", brand: "MAGIC MOVEMENT", size: "90ml" },
    { id: 135, name: "MAGIC MOVEMENT 60ML", brand: "MAGIC MOVEMENT", size: "60ml" },
    { id: 136, name: "MAGIC MOVEMENT 30ML", brand: "MAGIC MOVEMENT", size: "30ml" },
    { id: 137, name: "MAGIC MOVEMENT APPLE 180ML", brand: "MAGIC MOVEMENT APPLE", size: "180ml" },
    { id: 138, name: "MAGIC MOVEMENT APPLE 90ML", brand: "MAGIC MOVEMENT APPLE", size: "90ml" },
    { id: 139, name: "MAGIC MOVEMENT APPLE 60ML", brand: "MAGIC MOVEMENT APPLE", size: "60ml" },
    { id: 140, name: "MAGIC MOVEMENT APPLE 30ML", brand: "MAGIC MOVEMENT APPLE", size: "30ml" },
    { id: 141, name: "MAGIC MOVEMENT JAMUN 180ML", brand: "MAGIC MOVEMENT JAMUN", size: "180ml" },
    { id: 142, name: "MAGIC MOVEMENT JAMUN 90ML", brand: "MAGIC MOVEMENT JAMUN", size: "90ml" },
    { id: 143, name: "MAGIC MOVEMENT JAMUN 60ML", brand: "MAGIC MOVEMENT JAMUN", size: "60ml" },
    { id: 144, name: "MAGIC MOVEMENT JAMUN 30ML", brand: "MAGIC MOVEMENT JAMUN", size: "30ml" },
    { id: 145, name: "OLD MONK 180ML", brand: "OLD MONK", size: "180ml" },
    { id: 146, name: "OLD MONK 90ML", brand: "OLD MONK", size: "90ml" },
    { id: 147, name: "OLD MONK 60ML", brand: "OLD MONK", size: "60ml" },
    { id: 148, name: "OLD MONK 30ML", brand: "OLD MONK", size: "30ml" },
    { id: 149, name: "BACARDI WHITE 180ML", brand: "BACARDI WHITE", size: "180ml" },
    { id: 150, name: "BACARDI WHITE 90ML", brand: "BACARDI WHITE", size: "90ml" },
    { id: 151, name: "BACARDI WHITE 60ML", brand: "BACARDI WHITE", size: "60ml" },
    { id: 152, name: "BACARDI WHITE 30ML", brand: "BACARDI WHITE", size: "30ml" },
    { id: 153, name: "BACARDI LEMON 180ML", brand: "BACARDI LEMON", size: "180ml" },
    { id: 154, name: "BACARDI LEMON 90ML", brand: "BACARDI LEMON", size: "90ml" },
    { id: 155, name: "BACARDI LEMON 60ML", brand: "BACARDI LEMON", size: "60ml" },
    { id: 156, name: "BACARDI LEMON 30ML", brand: "BACARDI LEMON", size: "30ml" },
    { id: 157, name: "BACARDI BLACK 180ML", brand: "BACARDI BLACK", size: "180ml" },
    { id: 158, name: "BACARDI BLACK 90ML", brand: "BACARDI BLACK", size: "90ml" },
    { id: 159, name: "BACARDI BLACK 60ML", brand: "BACARDI BLACK", size: "60ml" },
    { id: 160, name: "BACARDI BLACK 30ML", brand: "BACARDI BLACK", size: "30ml" },
    { id: 161, name: "BLUE RIBAND 180ML", brand: "BLUE RIBAND", size: "180ml" },
    { id: 162, name: "BLUE RIBAND 90ML", brand: "BLUE RIBAND", size: "90ml" },
    { id: 163, name: "BLUE RIBAND 60ML", brand: "BLUE RIBAND", size: "60ml" },
    { id: 164, name: "BLUE RIBAND 30ML", brand: "BLUE RIBAND", size: "30ml" },
    { id: 165, name: "BOMBAY SAPPHIRE 180ML", brand: "BOMBAY SAPPHIRE", size: "180ml" },
    { id: 166, name: "BOMBAY SAPPHIRE 90ML", brand: "BOMBAY SAPPHIRE", size: "90ml" },
    { id: 167, name: "BOMBAY SAPPHIRE 60ML", brand: "BOMBAY SAPPHIRE", size: "60ml" },
    { id: 168, name: "BOMBAY SAPPHIRE 30ML", brand: "BOMBAY SAPPHIRE", size: "30ml" },
    { id: 169, name: "GRATER THAN 180ML", brand: "GRATER THAN", size: "180ml" },
    { id: 170, name: "GRATER THAN 90ML", brand: "GRATER THAN", size: "90ml" },
    { id: 171, name: "GRATER THAN 60ML", brand: "GRATER THAN", size: "60ml" },
    { id: 172, name: "GRATER THAN 30ML", brand: "GRATER THAN", size: "30ml" },
    { id: 173, name: "SHORT STORY 180ML", brand: "SHORT STORY", size: "180ml" },
    { id: 174, name: "SHORT STORY 90ML", brand: "SHORT STORY", size: "90ml" },
    { id: 175, name: "SHORT STORY 60ML", brand: "SHORT STORY", size: "60ml" },
    { id: 176, name: "SHORT STORY 30ML", brand: "SHORT STORY", size: "30ml" },
    { id: 177, name: "JAGERMEISTER 180ML", brand: "JAGERMEISTER", size: "180ml" },
    { id: 178, name: "JAGERMEISTER 90ML", brand: "JAGERMEISTER", size: "90ml" },
    { id: 179, name: "JAGERMEISTER 60ML", brand: "JAGERMEISTER", size: "60ml" },
    { id: 180, name: "JAGERMEISTER 30ML", brand: "JAGERMEISTER", size: "30ml" },
    { id: 181, name: "CAMINO 180ML", brand: "CAMINO", size: "180ml" },
    { id: 182, name: "CAMINO 90ML", brand: "CAMINO", size: "90ml" },
    { id: 183, name: "CAMINO 60ML", brand: "CAMINO", size: "60ml" },
    { id: 184, name: "CAMINO 30ML", brand: "CAMINO", size: "30ml" },
    { id: 185, name: "SULA SHIRAZ CABERNET 180ML", brand: "SULA SHIRAZ CABERNET", size: "180ml" },
    { id: 186, name: "SULA SHIRAZ CABERNET 90ML", brand: "SULA SHIRAZ CABERNET", size: "90ml" },
    { id: 187, name: "SULA SHIRAZ CABERNET 60ML", brand: "SULA SHIRAZ CABERNET", size: "60ml" },
    { id: 188, name: "SULA SHIRAZ CABERNET 30ML", brand: "SULA SHIRAZ CABERNET", size: "30ml" },
    { id: 189, name: "SULA CHENIN BLANC 180ML", brand: "SULA CHENIN BLANC", size: "180ml" },
    { id: 190, name: "SULA CHENIN BLANC 90ML", brand: "SULA CHENIN BLANC", size: "90ml" },
    { id: 191, name: "SULA CHENIN BLANC 60ML", brand: "SULA CHENIN BLANC", size: "60ml" },
    { id: 192, name: "SULA CHENIN BLANC 30ML", brand: "SULA CHENIN BLANC", size: "30ml" },
    { id: 193, name: "SULA SAMARA 180ML", brand: "SULA SAMARA", size: "180ml" },
    { id: 194, name: "SULA SAMARA 90ML", brand: "SULA SAMARA", size: "90ml" },
    { id: 195, name: "SULA SAMARA 60ML", brand: "SULA SAMARA", size: "60ml" },
    { id: 196, name: "SULA SAMARA 30ML", brand: "SULA SAMARA", size: "30ml" },
    { id: 197, name: "PORT WINE 180ML", brand: "PORT WINE", size: "180ml" },
    { id: 198, name: "PORT WINE 90ML", brand: "PORT WINE", size: "90ml" },
    { id: 199, name: "PORT WINE 60ML", brand: "PORT WINE", size: "60ml" },
    { id: 200, name: "PORT WINE 30ML", brand: "PORT WINE", size: "30ml" },
    { id: 201, name: "BREEZER CRANBERRY 330ML", brand: "BREEZER CRANBERRY", size: "330ml" },
    { id: 202, name: "BREEZER BLACKBERRY 330ML", brand: "BREEZER BLACKBERRY", size: "330ml" },
    { id: 203, name: "BREEZER BLUEBERRY 330ML", brand: "BREEZER BLUEBERRY", size: "330ml" },
    { id: 204, name: "BREEZER JAMICAN PASSION 330ML", brand: "BREEZER JAMICAN PASSION", size: "330ml" },
    { id: 205, name: "TUBORG S 650ML", brand: "TUBORG S", size: "650ml" },
    { id: 206, name: "TUBORG S 500ML", brand: "TUBORG S", size: "500ml" },
    { id: 207, name: "KINGFISHER S 650ML", brand: "KINGFISHER S", size: "650ml" },
    { id: 208, name: "KINGFISHER S 500ML", brand: "KINGFISHER S", size: "500ml" },
    { id: 209, name: "KINGFISHER S 330ML", brand: "KINGFISHER S", size: "330ml" },
    { id: 210, name: "CALSBURG ELEPHANT 650ML", brand: "CALSBURG ELEPHANT", size: "650ml" },
    { id: 211, name: "CALSBURG ELEPHANT 500ML", brand: "CALSBURG ELEPHANT", size: "500ml" },
    { id: 212, name: "BUDWISER MAGNUM 650ML", brand: "BUDWISER MAGNUM", size: "650ml" },
    { id: 213, name: "BUDWISER MAGNUM 500ML", brand: "BUDWISER MAGNUM", size: "500ml" },
    { id: 214, name: "LP S 650ML", brand: "LP S", size: "650ml" },
    { id: 215, name: "LP S 500ML", brand: "LP S", size: "500ml" },
    { id: 216, name: "TUBORG M 650ML", brand: "TUBORG M", size: "650ml" },
    { id: 217, name: "TUBORG M 500ML", brand: "TUBORG M", size: "500ml" },
    { id: 218, name: "KINGFISHER M 650ML", brand: "KINGFISHER M", size: "650ml" },
    { id: 219, name: "KINGFISHER M 500ML", brand: "KINGFISHER M", size: "500ml" },
    { id: 220, name: "KINGFISHER M 330ML", brand: "KINGFISHER M", size: "330ml" },
    { id: 221, name: "CALSBURG M 650ML", brand: "CALSBURG M", size: "650ml" },
    { id: 222, name: "CALSBURG M 500ML", brand: "CALSBURG M", size: "500ml" },
    { id: 223, name: "BUDWISER M 650ML", brand: "BUDWISER M", size: "650ml" },
    { id: 224, name: "BUDWISER M 500ML", brand: "BUDWISER M", size: "500ml" },
    { id: 225, name: "LP M 650ML", brand: "LP M", size: "650ml" },
    { id: 226, name: "LP M 500ML", brand: "LP M", size: "500ml" },
    { id: 227, name: "DR. BRANDY 180ML", brand: "DR. BRANDY", size: "180ml" },
    { id: 228, name: "DR. BRANDY 90ML", brand: "DR. BRANDY", size: "90ml" },
    { id: 229, name: "DR. BRANDY 60ML", brand: "DR. BRANDY", size: "60ml" },
    { id: 230, name: "DR. BRANDY 30ML", brand: "DR. BRANDY", size: "30ml" },
];

export default liquorItems;